### ISSUE TITLE
Inconsistency in problem block question text after saving problem

### ISSUE THREAD

**Issue by zahid-arbisoft** [openedx/frontend-lib-content-components#172]
Inconsistency in problem block question text after saving problem

Once you save question how it looks in studio. You can see bold text moved to the start of the line, instead of its actual position
![Screenshot 2022-12-21 at 2 48 11 PM](https://user-images.githubusercontent.com/31304505/208875178-83e40ded-f336-4bb1-adec-f4a2461f983c.png)

If you try to edit again, you will see text style not applied correctly

![Screenshot 2022-12-21 at 2 48 29 PM](https://user-images.githubusercontent.com/31304505/208875172-83e00389-927a-438b-8576-fcf603e56cc4.png)

@farhaanbukhsh

**Comment by farhaanbukhsh** [comment]
@zahid-arbisoft Thanks for reporting this issues, can you provide me the steps to reproduce this it?

**Comment by zahid-arbisoft** [comment]
https://user-images.githubusercontent.com/31304505/208910845-e2faac96-5e47-41c9-9ffe-51965db1ab37.mov

**Comment by zahid-arbisoft** [comment]
@farhaanbukhsh 
https://user-images.githubusercontent.com/31304505/208911780-e1e07192-9ce7-40b9-bdf0-b1757da6a724.mov

**Comment by zahid-arbisoft** [comment]
https://user-images.githubusercontent.com/31304505/208911907-6aa6bda6-0912-4db8-9506-3800e3bab3ff.mov

@farhaanbukhsh
