### ISSUE TITLE
SelectableBox component not selectable

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-lib-content-components#464]
## Description

2U's update of course-authoring to the openedx@21.5.7 version of paragon caused a bug where selectableboxes were not clickable or selectable. This occurred on their stage server and is very hard to reproduce locally, but looks to be tied to the paragon component since it only happens in the newer version and affects every place the component is used. 

See https://github.com/openedx/paragon/issues/3015 for more details.  This issue is meant to track actions to be taken for this repository.

## Steps

- [x] https://github.com/openedx/frontend-lib-content-components/pull/459
- [x] https://github.com/openedx/frontend-lib-content-components/pull/460
- [x] https://github.com/openedx/frontend-lib-content-components/pull/461
- [x] https://github.com/openedx/frontend-lib-content-components/pull/462
- [ ] Once the issue is fixed upstream, remove the component override introduced here

**Comment by bradenmacdonald** [comment]
Closing this as the code has been moved into course-authoring and we have https://github.com/openedx/frontend-app-course-authoring/issues/891 to track it in the new repo.
