### ISSUE TITLE
Feedback link is hardcoded to a 2U Google Form

### ISSUE THREAD

**Issue by kdmccormick** [openedx/frontend-lib-content-components#476]
The "Share Feedback" link:

![image](https://github.com/openedx/frontend-lib-content-components/assets/3628148/c6f33e9e-ca6a-49af-ba87-22d95e2c1bb3)

Goes to:

![image](https://github.com/openedx/frontend-lib-content-components/assets/3628148/5352f6a7-54ed-4d38-b776-fc7d7bb40416)

We can't be directing Open edX users to a form hosted on 2U's Google account.

**Comment by kdmccormick** [comment]
Thanks for the fix @KristinAoki . Could you backport this to Redwood as well?

**Comment by mariajgrimaldi** [comment]
I'll close this as completed since it was backported successfully to redwood. Thank you!
