### ISSUE TITLE
Unlimited attempts cannot be updated in problem editor

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/frontend-lib-content-components#480]
### Expected behavior

As a course author, I want to set up a problem with unlimited attempts, so that students can submit their answers as many times as they want.

### Actual behavior

As a course author, I cannot assign a problem with unlimited attempts. It happens when you already have a set number of attempts and want to change to unlimited attempts.

### Steps to reproduce

1. From **Studio** create a problem.
2. Configure the problem with a number of attempts, e.g.: `5`, and save.
3. Edit the problem try to assign unlimited attempts, and save
4. The problem continues to have the same number of attempts assigned previously

https://github.com/openedx/wg-build-test-release/assets/64033729/f722b3a2-ed43-4081-ac13-dd84c7008291

### Additional information

It happens in all problems, but it does not happen with the legacy editor.

Original issue: https://github.com/openedx/wg-build-test-release/issues/371

**Comment by mariajgrimaldi** [comment]
Here's what I've found:
- This happens even without publishing the unit
- When selecting unlimited attempts after setting a limited attempts to any number, the request doesn't include the unlimited attempt change:
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/860b6da1-f3c0-4545-b06b-dcb6572d5292)
- When changing the number of attempts, it sends the new change accordingly:
![image](https://github.com/openedx/wg-build-test-release/assets/64440265/ddfb8577-ed47-47ec-8b8a-a663ec96b75a)

I'll be reporting this in the frontend-lib-content-components repo.

**Comment by mariajgrimaldi** [comment]
FYI @arbrandes @brian-smith-tcril @openedx/2u-tnl, please tag anyone who can help.

**Comment by brian-smith-tcril** [comment]
in some quick testing on the sandbox using the network tab in the browser inspector (filtering to `method:POST`) I was able to find that checking "unlimited attempts" sends nothing for `max_attempts` in the `metadata` part of the payload. By manually entering `0` for number of attempts I was able to get the "You have used 0 of x attempts" message to go away.

**Comment by mariajgrimaldi** [comment]
@brian-smith-tcril: Exactly, thanks for testing it out! I mentioned something similar in the comment I left [here](https://github.com/openedx/frontend-lib-content-components/issues/480#issuecomment-2141201587). However, I'm not sure why setting unlimited attempts first works sending the correct metadata but not changing it to unlimited.

**Comment by brian-smith-tcril** [comment]
I believe it defaults to zero if no `max_attempts` value is submitted when creating the problem, but not sending a value for `max_attempts` when editing is interpreted as "don't change the value for `max_attempts`"

**Comment by mariajgrimaldi** [comment]
@brian-smith-tcril right! Thank you :))

**Comment by mariajgrimaldi** [comment]
I was testing around in the quince sandbox and I couldn't reproduce the error there:
![image](https://github.com/openedx/frontend-lib-content-components/assets/64440265/9caf86f2-f422-497d-815f-8d3f21665a19)
See how the max_attempts is set to "" when selecting unlimited attempts.

**Comment by mariajgrimaldi** [comment]
@KristinAoki thank you so much for taking care of this! I have a question, though: how can we backport this to the redwood release?

**Comment by KristinAoki** [comment]
@mariajgrimaldi The change was included in https://github.com/openedx/frontend-app-course-authoring/pull/1071 which upgrades the npm pack for course authoring. I think that the upgrade PR might needs to be backported, but not 100% sure.

**Comment by mariajgrimaldi** [comment]
@KristinAoki: I created the backport, I hope that's enough! https://github.com/openedx/frontend-app-course-authoring/pull/1075
