### ISSUE TITLE
Node 20 Upgrade

### ISSUE THREAD

**Issue by BilalQamar95** [openedx/frontend-lib-content-components#503]
### Description

Part of https://github.com/openedx/public-engineering/issues/232. See https://github.com/openedx/public-engineering/issues/267 for the general description and motivation.  Make sure to follow its recommendations for each step of the process.

```[tasklist]
- [ ] https://github.com/openedx/frontend-lib-content-components/pull/504
- [ ] https://github.com/openedx/frontend-lib-content-components/pull/495
- [ ] test: Remove Node 18 from the CI matrix ([example PR](https://github.com/openedx/frontend-template-application/pull/745))
```

**Comment by KristinAoki** [comment]
Closing this issue because this repo will be merged into frontend-app-course-authoring which already has this upgrade in progress.
